# Generated by Django 4.0.6 on 2022-08-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostel', '0007_rename_name_hostelite_first_name_hostelite_email_and_more'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('later', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelite')),
                ('sic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.register')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomate1', models.CharField(max_length=20)),
                ('roomate2', models.CharField(max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.room')),
            ],
        ),
    ]
