# Generated by Django 4.0.6 on 2022-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectmatch',
            name='later',
            field=models.IntegerField(),
        ),
    ]
