# Generated by Django 4.0.6 on 2022-08-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_alter_selectmatch_later'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='roomate1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='roomate2',
            field=models.IntegerField(),
        ),
    ]
