# Generated by Django 4.0.6 on 2022-08-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_alter_match_roomate1_alter_match_roomate2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='status2',
            field=models.BooleanField(default=False),
        ),
    ]
