# Generated by Django 4.0.6 on 2022-08-25 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('matcher', '0005_remove_match_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='status1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='status2',
        ),
        migrations.AddField(
            model_name='match',
            name='room_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectmatch',
            name='status1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selectmatch',
            name='status2',
            field=models.BooleanField(default=False),
        ),
    ]
